### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [Baron-von-Riedesel/HimemSX#1]
Hey there!

Just a thought: A function which allows the calling application to specify the location in memory of the handle would be helpful to access certain hardware directly.

For example, currently, an application storing its graphics in XMS needs to use the XMS driver to copy sprites or other image data into an intermediate buffer, then it will use the VESA block transfer call to blit the buffer to the actual screen in several chunks, which adds significant overhead to each frame.

If we think about it, though, this doesn't need to be. Using VESA calls, the application will already know where the VESA Frame Buffer "lives" and how big it is. "Direct handles" would allow that application to set up an XMS handle which directly addresses the VESA Linear Frame Buffer and eliminate the additional function calls needed to transfer an off-screen buffer to the display.

Such a function would work something like this:
```
AH=0CDh: Set up "direct handle" to arbitrary block of memory.
ECX: The size of the memory block in kB.
EDX: The address of the block.
Returns AX=0 if an error occurred, else AX is 1 and the handle of the block is in DX.
```

But anyway, keep up the awesome work on this and I hope this suggestion proves useful! :)

**Comment by Baron-von-Riedesel** [comment]
I understand the benefits, but actually, an application can always lock the xms-block and then do the more direct transfer on its own. And himemsx should be kept as small as possible.
