### ISSUE TITLE
XMS 3.5 and 3.51

### ISSUE THREAD

**Issue by DosWorld** [Baron-von-Riedesel/HimemSX#3]
Hello, Japheth!

I want purpose some changes:

1. Here is no **realloc** function.
2. **sxms_move** struct does not have "**len_high** db  ?" (for case when copy xms -> xms)

PS: IMHO, "**_high**" will be better define as "DD" instead "DB". I am optimist. :)

**Comment by Baron-von-Riedesel** [comment]
> Here is no realloc function.

not needed, old function 8Fh works for any handle.

> sxms_move struct does not have "len_high db ?" (for case when copy xms -> xms)

Yes - in such a case you'll have to call the move function multiple times. This isn't a problem, is it?
